### PR TITLE
Feature/activity api

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@alexey-rise I know it is a long review but I don't see a better way to do that. I guess it is easier to review the project as whole instead of only the commits. 

You can check it working here: https://apis-explorer.appspot.com/apis-explorer/?base=https://monitoring-dot-rvacore-test.appspot.com/_ah/api#p/monitoring/v0/

Let me know if you have any question or idea.

Cheers.

### CODE REVIEW

**Comment by alexey-rise** [comment]
@rodrigopavezi see https://github.com/Rise-Vision/core/issues/120, looks like you will have to rethink the idea of looking up client ID in the API call as it appears to randomly increase latency.

**Comment by rodrigopavezi** [comment]
@alexey-rise could you please review? cheers!

**Comment by alexey-rise** [comment]
@rodrigopavezi curious, why did you remove the user authentication from the monitoring API?

**Comment by rodrigopavezi** [comment]
@alexey-rise do you mean checking the user against the rva register users?

**Comment by alexey-rise** [comment]
@rodrigopavezi I mean removing the `User user` parameter from the accessor.

**Comment by rodrigopavezi** [comment]
@alexey-rise I removed it because It was only used it for changedBy field of the datastore entity. The only thing the api is doing now is making sure that the user is not null. Do you think we should check if the user is register with us? cheers

**Comment by alexey-rise** [comment]
@rodrigopavezi how are you going to make sure that people only see their company's and subcompanies' monitoring data?

**Comment by rodrigopavezi** [comment]
@alexey-rise as the api is closed and the only application that can access it is the common-header. this is already filtered on common-header. If that does not satisfy I can implement a call to the verifyUser on core. To be honest I think we can look on this later on after release 1.  what do you think?

**Comment by alexey-rise** [comment]
@rodrigopavezi I understand that you can only see if from CH, what I am concerned about is someone using CH to view somebody else's monitoring data. Are you saying it's 100% impossible?

We don't actually know when monitoring release 2 is coming out do we? I am not very comfortable leaving a security hole open for an indefinite period of time. 

@ByronDarlison how important is it to secure monitoring data?

**Comment by ByronDarlison** [comment]
@alexey-rise @rodrigopavezi I would prefer not to leave holes. Thanks

**Comment by rodrigopavezi** [comment]
@alexey-rise @ByronDarlison sure, I will try to get this done by Monday. @alexey-rise what do you think about creating a verifyUserForApp api endpoint on riseAPI? cheers

**Comment by alexey-rise** [comment]
@rodrigopavezi why can't you use `rise.user.verifyAccess`?

**Comment by rodrigopavezi** [comment]
@alexey-rise we don't have the company id of an app on monitoring service. We don't even have an app entity. we have only a clientId. So, we have to get the company id and the app entity from core based on the clientId. I was thinking that we can call the verifyUserForApp with a user and a clientId. This method will get the app entity for the clientId, the app entity comes with a company id which we use to verify the access of it by the userId. cheers

**Comment by rodrigopavezi** [comment]
@alexey-rise we can make two calls as well. One to an app.get by clientId (we have to implement it). Another to the verifyUser with the retrieved apps companyId and userId.  What do you think about this way? cheers

**Comment by alexey-rise** [comment]
@rodrigopavezi I think 2 calls make more sense, that way you don't have to repeat the user verification functionality, you just need to implement the clientId to companyId lookup.

**Comment by rodrigopavezi** [comment]
@alexey-rise cool, I will implement that then. cheers.

**Comment by rodrigopavezi** [comment]
@alexey-rise could you please review the private key PR https://github.com/Rise-Vision/private-keys/pull/7 so this PR build can pass on cci? 

I have also finished the user access verification for the apps company. Feel free to review the latest changes and after your green sign we should be good to ship the monitoring release 1.

Cheers.

**Comment by alexey-rise** [comment]
:+1: I reviewed the private keys PR but somehow I missed this. Sorry about that!

**Comment by rodrigopavezi** [comment]
@alexey-rise no problem, cheers!!

**Pull request merged**
